service: aimock

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: "eu-central-1"

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  answers:
    handler: bin/answers
    events:
      - http:
          path: /answers
          method: POST
          cors: true